from __future__ import absolute_import

NOT_IN_ROOM = "You are not in this room."
NO_SESSKEY = "No session key."
NO_TEXT = "No text."
INVALID_ROOM = "Invalid room."
INVALID_SESSKEY = "Invalid session key."
ALREADY_IN_ROOM = "Already in room."
NO_USERNAME = "No username."
NO_PASSWORD = "No password."
INVALID_LOGIN = "Invalid username/password combination."
TOO_LONG = "This sentence is too long."
NO_ROUND = "There does not appear to be a round."
NO_MAKING = "Making sentences is not allowed at this time."
INVALID_WORD = "Invalid word: %s"
NO_SENTENCE = "No sentence chosen to vote for."
INVALID_SENTENCE = "Invalid sentence ID."
NO_VOTE_SELF = "You can't vote for yourself."
NO_SENTENCE_SUBMITTED = "You didn't submit a sentence!"
NO_VOTING = "No voting is allowed at this time."
